window.LAOGUAN_CONFIG = window.LAOGUAN_CONFIG || {};
window.LAOGUAN_CONFIG.AMAP_KEY = window.LAOGUAN_CONFIG.AMAP_KEY || "";
window.LAOGUAN_CONFIG.AMAP_SECURITY_JS_CODE =
  window.LAOGUAN_CONFIG.AMAP_SECURITY_JS_CODE || "";
window.LAOGUAN_CONFIG.AMAP_SERVICE_KEY =
  window.LAOGUAN_CONFIG.AMAP_SERVICE_KEY || window.LAOGUAN_CONFIG.AMAP_KEY || "";
